apiVersion: v1
kind: Namespace
metadata:
  name: frontend-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-app
  namespace: frontend-ns
data:
  requirements.txt: |
    Flask==2.3.0
    flask-cors==4.0.0
  app.py: |
    from flask import Flask, request, jsonify
    from flask_cors import CORS
    import sys
    
    app = Flask(__name__)
    CORS(app)
    
    @app.route('/health', methods=['GET'])
    def health():
        return jsonify({"status": "ok"}), 200
    
    @app.route('/add', methods=['POST'])
    def add():
        try:
            data = request.json
            num1 = int(data.get('num1', 0))
            num2 = int(data.get('num2', 0))
            result = num1 + num2
            return jsonify({"result": result, "status": "success"}), 200
        except Exception as e:
            return jsonify({"error": str(e), "status": "error"}), 400
    
    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5000, debug=False, threaded=True)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: frontend-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - backend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: python-backend
        image: python:3.9-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            cd /app && \
            pip install --no-cache-dir -r requirements.txt && \
            python app.py
        volumeMounts:
        - name: app-code
          mountPath: /app
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: app-code
        configMap:
          name: backend-app
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: frontend-ns
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-nodeport
  namespace: frontend-ns
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: frontend-ns
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kubernetes Calculator</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 50px; }
            input { padding: 5px; margin: 5px; }
            button { padding: 5px 15px; margin: 5px; background-color: #4CAF50; color: white; }
            h3 { color: green; }
        </style>
    </head>
    <body>
        <h2>Kubernetes Calculator</h2>
        <input id="a" type="number" placeholder="Number 1"> +
        <input id="b" type="number" placeholder="Number 2">
        <button onclick="calc()">Calculate Sum</button>
        <h3 id="res">Result will appear here</h3>
        <script>
        async function calc() {
            const valA = document.getElementById('a').value;
            const valB = document.getElementById('b').value;
            
            if (!valA || !valB) {
                document.getElementById('res').innerText = 'Please enter both numbers';
                return;
            }
            
            try {
                const backendUrl = 'http://' + window.location.hostname + ':30002/add';
                console.log('Calling: ' + backendUrl);
                const response = await fetch(backendUrl, {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify({num1: valA, num2: valB})
                });
                const data = await response.json();
                if (data.status === 'success') {
                    document.getElementById('res').innerText = 'Result: ' + data.result;
                } else {
                    document.getElementById('res').innerText = 'Error: ' + data.error;
                }
            } catch (err) {
                document.getElementById('res').innerText = 'Error: Cannot reach backend';
                console.error(err);
            }
        }
        </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - frontend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx-frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: html
        configMap:
          name: frontend-html
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-ns
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
